---
deployment:
  tasks:
    - export DEPLOYPATH=/home/naatioc1/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R theme-icon $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH